version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: karazin
      MYSQL_USER: karazin
      MYSQL_PASSWORD: test123
    ports:
      - "3306:3306"
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      APACHE_PORT: 8000
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
  backend:
    env_file:
      - backend/.env
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "5050:5050"
  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "80:80"